version: '{build}'

skip_tags: false

pull_requests:

  do_not_increment_build_number: true

deploy:

- provider: GitHub
  release: $(APPVEYOR_REPO_TAG_NAME)
  description: Weekly Pre-release
  prerelease: true
  draft: true
  auth_token:
    secure: m8kBg3jFX2k516nlmWkvxNCrBwlQZMaa6hNn7A+rktl781BRTyKssCXQqKAwPJLs
  artifact: executable
  on:
    appveyor_repo_tag: true

environment:

  global:
    PIP_ACCEL_LOG_FORMAT: "%(name)-18s %(levelname)s %(message)s"

  matrix:

    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "32"
    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "32"

cache:
  # Keep cache of downloaded pip packages.
  - C:\Users\appveyor\AppData\Local\pip
  # Keep downloaded packages.
  - C:\Dist

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:

  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  - "python --version"

  # Setup the rest of the environment.
  - "python windows\\helper.py setup"

  - "pip --disable-pip-version-check list"

build:
  verbosity: minimal

before_build:
  # Update version number from VCS.
  - "python setup.py patch_version"

build_script:
  - "python setup.py build"

after_build:
  - ps: "if ($Env:PYTHON_VERSION -eq \"3.5\") { python windows\\helper.py dist }"

test_script:
  - "python setup.py test"

artifacts:

  - path: dist\*.exe
    name: executable

