version: '{build}'

skip_tags: false

pull_requests:

  do_not_increment_build_number: true

deploy:

- provider: GitHub
  release: $(APPVEYOR_REPO_TAG_NAME)
  description: Weekly Pre-release
  prerelease: true
  draft: true
  auth_token:
    secure: m8kBg3jFX2k516nlmWkvxNCrBwlQZMaa6hNn7A+rktl781BRTyKssCXQqKAwPJLs
  on:
    appveyor_repo_tag: true

environment:

  global:
    PIP_ACCEL_LOG_FORMAT: "%(name)-18s %(levelname)s %(message)s"

  matrix:

    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "32"

cache:
  - .cache

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:

  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python --version"
  # Add Nullsoft Scriptable Install System to the PATH.
  - "SET PATH=C:\\Program Files (x86)\\NSIS;%PATH%"
  # Setup the rest of the environment.
  - "python -m utils.get_pip"
  - "python -m utils.install_wheels -r requirements.txt"
  - "python -m pip list --format=freeze"

build:
  verbosity: minimal

before_build:
  # Update version number from VCS.
  - "python setup.py patch_version"

build_script:
  - "python setup.py build"

test_script:
  - "python setup.py test"

after_test:
  - "python setup.py bdist_win -t -z -i"

artifacts:

  - path: dist\*.exe
    name: installer

  - path: dist\*.zip
    name: all-in-one zip

